# Pull from postgres docker hub image
FROM postgres:12

# Expose default postgres port
EXPOSE 5432

# Set default environment variables
ENV POSTGRES_PASSWORD=pbfalcon.dev.admin
ENV POSTGRES_USER=4630_user
ENV POSTGRES_DB=crmDB
